### ISSUE TITLE
Sample bundle cannot be instantiated.

### ISSUE THREAD

**Issue by xbrianh** [HumanCellAtlas/metadata-api#12]
Not sure if this is a bug or a problem with sample bundle file.

A bundle containing the file `sequence_file_0.json`, with the following contents, throws the error shown at the end of this ticket. This is because the path `file_core.file_name` does not equal the file name.
```
{
  "describedBy": "https://schema.humancellatlas.org/type/file/6.1.1/sequence_file",
  "schema_type": "file",
  "file_core": {
    "file_name": "R1.fastq.gz",
    "file_format": "fastq.gz"
  },
  "read_index": "read1",
  "lane_index": 1,
  "provenance": {
    "document_id": "c2c44dd4-7fb3-410e-a765-37c6331e97b4",
    "submission_date": "2018-07-22T23:38:35.990Z",
    "update_date": "2018-07-22T23:39:37.628Z"
  }
}
```

Error:
```
Traceback (most recent call last):
  File "green_bundle_is_valid.py", line 15, in <module>
    bundle = Bundle(ss2_bundle_id, version, manifest, metadata_files)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 533, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 527, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 496, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 496, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 495, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 35, in from_json
    return sub_cls(json, **kwargs)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 425, in __init__
    super().__init__(json, manifest)
  File "/Users/xath/.virtualenvs/data-store/lib/python3.6/site-packages/humancellatlas/data/metadata/__init__.py", line 405, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R1.fastq.gz'
```

@hannes-ucsc

**Comment by xbrianh** [comment]
nm, this looks like a misapprehension on my part.
