### ISSUE TITLE
Absorb addition of paging to `GET /bundles/{uuid}` in DSS

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#73]
```
[WARNING]    2019-05-03T10:53:15.720Z    898e5130-ff13-5e81-93eb-0476e0a91d71    Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': '36'}}, {'bool': {'should': [{'terms': {'files.project_json.provenance.document_id': ['2c4724a4-7252-409e-b008-ff5c127c7e89', '08e7b6ba-5825-47e9-be2d-7978533c5f8c', '019a935b-ea35-4d83-be75-e1a688179328', 'a5ae0428-476c-46d2-a9f2-aad955b149aa', 'adabd2bd-3968-4e77-b0df-f200f7351661', '67bc798b-a34a-4104-8cab-cad648471f69', '81b5f43d-3c20-4575-9efa-bfb0b070a6e3', '519b58ef-6462-4ed3-8c0d-375b54f53c31', '2cd14cf5-f8e0-4c97-91a2-9e8957f41ea8', '1f9a699a-262c-40a0-8b2c-7ba960ca388c', '62aa3211-bf52-4873-9029-0bcc1d09e553', 'a71dee10-9a4d-4ea2-a6f3-ae7314112cf1', 'adb384b2-cd5e-4cf5-9205-5f066474005f', '46c58e08-4518-4e45-acfe-bdab2434975d', '3eaad325-3666-4b65-a4ed-e23ff71222c1']}}, {'range': {'manifest.version': {'gte': '2019-04-03', 'lte': '2019-04-17'}}}], 'must_not': [{'terms': {'uuid': ['4d939743-d276-4c78-a392-b2ead842c149', '67b859c2-ab56-457c-9da0-3445c150ce53']}}]}}]}}}, 'subscription_id': 'feeb0f2b-c16f-48f8-bac0-e6fd09b92320', 'transaction_id': 'feeb0f2b-c16f-48f8-bac0-e6fd09b92320', 'match': {'bundle_uuid': '365c5f87-460a-41bc-a690-70ae6b5dba54', 'bundle_version': '2018-10-17T092427.195428Z'}, 'test_name': None}}. Traceback (most recent call last): 
 File "/var/task/app.py", line 182, in index contributions = indexer.transform(notification) 
 File "/var/task/azul/indexer.py", line 103, in transform metadata_files=metadata_files)) 
 File "/var/task/azul/project/hca/transformers.py", line 431, in transform metadata_files=metadata_files) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 720, in __init__ self.files = from_json_vx(
 File, manifest=self.manifest) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 714, in from_json_vx return from_json(core_cls, json_entities, **kwargs) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 683, in from_json return {entity.document_id: entity for entity in entities} 
 File "/var/task/humancellatlas/data/metadata/api.py", line 683, in <dictcomp> return {entity.document_id: entity for entity in entities} 
 File "/var/task/humancellatlas/data/metadata/api.py", line 682, in <genexpr> entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json return sub_cls(json, **kwargs) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 601, in __init__ super().__init__(json, manifest) 
 File "/var/task/humancellatlas/data/metadata/api.py", line 575, in __init__ self.manifest_entry = manifest[core['file_name']] KeyError: 'AB4653.R1.fastq.gz
```

**Comment by hannes-ucsc** [comment]
Demoed on 6/3/2019
