### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#95]
Things to do:

- [ ] Make dependency on `dataclasses` backport conditional on Python 3.6 (see exception below).

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/humancellatlas/data/metadata/api.py", line 10, in <module>
    from humancellatlas.data.metadata.age_range import AgeRange
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/humancellatlas/data/metadata/age_range.py", line 6, in <module>
    @dataclass(frozen=True)
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/Users/hewgreen/google_drive_EBI/playground/metadata_api/foo/lib/python3.7/site-packages/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
```

Workaround is to `pip uninstall dataclasses`.

**Comment by hannes-ucsc** [comment]
Moved to https://github.com/DataBiosphere/hca-metadata-api/issues/6
